version: "3.9"
services:
  uh-data-node:
    image: uh-data-node
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_SERVER_DB
        - SRC_PATH=server-db
        - TARGET=uh-data-node
  uh-agency-node:
    image: uh-agency-node
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_SERVER_AGENCY
        - SRC_PATH=server-agency
        - TARGET=uh-agency-node
    ports:
      - "21832:21832"
    depends_on:
      - uh-data-node
    links:
      - uh-data-node
  uh-cli:
    image: uh-cli
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_CLIENT_SHELL
        - SRC_PATH=client-shell
        - TARGET=uh-cli
    ports:
      - "1337:1337/udp"
    depends_on:
      - uh-data-node
      - uh-agency-node
    links:
      - uh-agency-node