#ifndef IO_DATA_GENERATOR_H
#define IO_DATA_GENERATOR_H

#include <optional>
#include <span>
#include <vector>


namespace uh::io
{

// ---------------------------------------------------------------------

/**
 * Piece of data to be returned by `data_generator`. Can hold a vector
 * or a reference to some external buffer and makes it accessible through
 * a single function.
 *
 * class invariant: m_buffer.empty() != m_span.empty()
 */
class data_chunk
{
public:
    data_chunk(std::vector<char>&& buffer);
    data_chunk(std::span<char> span);

    std::span<char> data();
private:
    std::vector<char> m_buffer;
    std::span<char> m_span;
};

// ---------------------------------------------------------------------

class data_generator
{
public:
    virtual ~data_generator() = default;

    /**
     * Get the next sub-chunk. The function will return subchunk until
     * all subchunks are provided. If there are no more subchunks to
     * return `std::nullopt` will be returned.
     */
    virtual std::optional<data_chunk> next() = 0;

    /**
     * If possible, return the amount of data that will be generated by
     * this class in bytes.
     */
    virtual std::optional<std::size_t> size() = 0;
};

// ---------------------------------------------------------------------

} // namespace uh::io

#endif
