services:
  proxy:
    image: registry.ultihash.io/dev/core:ulticache-nightly-build
    environment:
      UH_LOG_LEVEL: INFO
      UH_OTEL_ENDPOINT: http://otel:4317
      UH_DB_HOSTPORT: database:5432
      UH_DB_USER: postgres
      UH_DB_PASS: uh
    command: ["/usr/bin/bash", "-l", "-c", "uh-cluster ---downstream-port 80 --downstream-host http://s3.eu-north-1.amazonaws.com proxy"]
    ports:
      - 8080:8080

