apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: performance-test-input
spec:
  storageClassName: ebs-csi-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: performance-test-output
spec:
  storageClassName: ebs-csi-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi