# Copyright 2026 UltiHash Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mode: distributed

global:
  storageClass: local-path

statefulset:
  replicaCount: 4
  zones: 1
  drivesPerNode: 1

auth:
  rootUser: admin
  rootPassword: "testpassword"

tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "testing"
    effect: "NoSchedule"

nodeSelector:
  workload-type: minio
  purpose: performance-testing-large

affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - minio
        topologyKey: kubernetes.io/hostname

resourcesPreset: none