# Copyright 2026 UltiHash Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Environment Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: lightweight-generic-jobs
    strategy:
      matrix:
        test_names: [simple-rr, simple-ec]
    steps:
      - name: Define testing environment name
        run: echo "ENVIRONMENT_NAME=pr-${{ github.event.pull_request.number }}-${{ matrix.test_names }}" >> $GITHUB_ENV

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.aws_access_key_id }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core
    
      - uses: azure/setup-helm@v4.3.0

      - name: Delete the testing environment
        run: |
          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait || true
          kubectl delete pvc -n ${{ env.ENVIRONMENT_NAME }} --all --force || true
          kubectl delete secrets -n ${{ env.ENVIRONMENT_NAME }} --all --force || true
          kubectl delete ns ${{ env.ENVIRONMENT_NAME }} || true