name: Integration Test (C++ Apps)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  integration-test-docker:
    runs-on: uh-x86_64-ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_E2E_TESTS=On

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --parallel $(nproc)

      - name: Test
        env:
          ETCDCTL_API: 3
        working-directory: ${{github.workspace}}/build
        run: |
          etcd&
          sleep 5
          etcdctl del "" --from-key=true
          ctest -C ${{ matrix.build }} --output-on-failure
          etcdctl del "" --from-key=true

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: LastTest.log
          path: ${{github.workspace}}/build/Testing/Temporary/LastTest.log
