name: Integration Test (C++ Apps)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  integration-test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: plauth
          password: ${{ secrets.PAT }}

      - name: Install tox
        run: sudo apt install tox

      - name: Running integration tests
        working-directory: ${{github.workspace}}/testing
        run: ./start-e2e.sh
