name: Integration Test (C++ Apps)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  integration-test-docker:
    runs-on: uh-x86_64-ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Install tox
        run: sudo apt install tox

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --parallel $(nproc)

      - name: Build Docker image
        run: docker build --file Dockerfile --tag ghcr.io/ultihash/cluster:$(printf '%(%Y%m%d)T' -1) .

      - name: Running integration tests
        working-directory: ${{github.workspace}}/testing
        run: ./start-e2e.sh
