name: Nightly Testing Workflow

on:
  push:

jobs:
  
  small-performance-test:
    uses: ./.github/workflows/performance_testing_small_aws.yml
    with:
      env_name: performance-testing-small-aarch64
      docker_image_tag: nightly-build
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      docker_registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      docker_registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      registry_token: ${{ secrets.REGISTRY_USER }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY}}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
      uh_license: ${{ secrets.UH_LICENSE_1PB }}
      monitoring_token: ${{ secrets.MONITORING_TOKEN_AWS }}
  