name: Provision Testing Environment

# Triggers on branch or tag creation
# Do not triger it on tag creation!
on:
  create:

jobs:
  creation:
    runs-on: lightweight-generic-jobs
    steps:

    - uses: azure/setup-kubectl@v3
      with:
        version: v1.28.7

    - name: Download Kubeconfig
      run: |
        mkdir ~/.kube
        echo '${{ secrets.KUBECONFIG }}' > ~/.kube/config

    - name: Setup namespace
      run: |
        kubectl create ns ${{ github.ref_name }}
        kubectl create secret docker-registry registry-credentials -n ${{ github.ref_name }} --docker-server='${{ vars.DOCKER_REGISTRY }}' --docker-username='${{ secrets.DOCKER_REGISTRY_USERNAME }}' --docker-password='${{ secrets.DOCKER_REGISTRY_PASSWORD }}'
        kubectl create secret generic ultihash  -n ${{ github.ref_name }} --from-literal=license='${{ secrets.UH_LICENSE }}'